title: Robert Hardege
description: Portfolio & Projects
url: 'https://roberthardege.de'
baseurl: ''

author:
  name: Robert Hardege
  email: kontakt@roberthardege.de

markdown: kramdown
theme: null
plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - vendor/
  - .claude/
